manifest:
  projects:
    - name: hpsnz_drivers
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.5.1
      import: true
    - name: pyrinas
      url: https://github.com/pyrinas-iot/pyrinas-zephyr
      revision: v1.5.x
      path: pyrinas
      import: true
  self:
    # This repository should be cloned to nrf9160-feather
    path: nfed